# Test con Example 6.7 - Kassimali

## Pórtico bidimensional
<img src="kex67.png">

## Modelo analítico
<img src="kex67_model.png">

In [1]:
import math

In [2]:
import analisa.edeb as edb

## Datos de nudos

In [3]:
# Datos de los nudos
coords = {1: (0,0), 2: (9, 0), 3: (0, 6), 4: (9, 6), 5: (0, 12)}  # Coordenadas de nudos
restricciones = {1: (1,1,1), 2: (1,1,1)}  # Apoyos

## Datos de barras

In [4]:
# Materiales
E = 30e9
m = edb.Material(E)

In [5]:
# Datos de las secciones
A = 75e-3  # área
I = 4.8e-4  # inercia
s = edb.Seccion(area=A, inercia_z=I)

In [6]:
# Conectividad
datos_barras = {1: (1,3), 2: (2,4), 3:(3,5), 4: (3,4), 5: (4,5)}

## Cargas

In [7]:
cargas_nodales = {3: (80e3, 0, 0), 5: (40e3, 0, 0)}

In [8]:
# Cargas en barras
ang = math.atan(6/9)
q = 12e3
qx = q*math.sin(ang)
qy = q*math.cos(ang)
cargas_barras = {5: (qx, qy)}

In [9]:
p = edb.Portico(datos_nudos=coords, restricciones=restricciones,
            datos_barras=datos_barras, materiales=m, secciones=s,
            cargas_nodales=cargas_nodales, cargas_barras=cargas_barras)

In [10]:
p.procesamiento()

Ensamble de matrices globales...
Resolución del problema estático...
Listo, preguntá lo que quieras.


In [11]:
p.rigidez_gdl()*1e-3

array([[ 2.51600000e+05,  0.00000000e+00,  0.00000000e+00,
        -2.50000000e+05,  0.00000000e+00,  0.00000000e+00,
        -8.00000000e+02,  0.00000000e+00, -2.40000000e+03],
       [ 0.00000000e+00,  7.50237037e+05,  1.06666667e+03,
         0.00000000e+00, -2.37037037e+02,  1.06666667e+03,
         0.00000000e+00, -3.75000000e+05,  0.00000000e+00],
       [ 0.00000000e+00,  1.06666667e+03,  2.56000000e+04,
         0.00000000e+00, -1.06666667e+03,  3.20000000e+03,
         2.40000000e+03,  0.00000000e+00,  4.80000000e+03],
       [-2.50000000e+05,  0.00000000e+00,  0.00000000e+00,
         3.94850718e+05, -9.59427840e+04,  1.99037524e+03,
        -1.44050718e+05,  9.59427840e+04, -4.09624760e+02],
       [ 0.00000000e+00, -2.37037037e+02, -1.06666667e+03,
        -9.59427840e+04,  4.39335435e+05, -1.68110381e+03,
         9.59427840e+04, -6.40983976e+04, -6.14437140e+02],
       [ 0.00000000e+00,  1.06666667e+03,  3.20000000e+03,
         1.99037524e+03, -1.68110381e+03,  2.132512

In [12]:
p.desplaz_gdl()

array([ 1.85423653e-01,  4.18738947e-04, -1.76198747e-02,  1.85521414e-01,
       -1.30738947e-04, -2.60284808e-02,  1.86623368e-01,  7.13669896e-04,
        1.78911956e-02])

In [13]:
p.reacciones()*1e-3

array([-106.05122292, -157.02710519,  360.44136804,  -85.94877708,
         49.02710519,  320.31468527])

In [14]:
b1 = p.barras()[0]

In [15]:
b1.rigidez_global*1e-3

array([[    800.,       0.,   -2400.,    -800.,       0.,   -2400.],
       [      0.,  375000.,       0.,       0., -375000.,       0.],
       [  -2400.,       0.,    9600.,    2400.,       0.,    4800.],
       [   -800.,       0.,    2400.,     800.,       0.,    2400.],
       [      0., -375000.,       0.,       0.,  375000.,       0.],
       [  -2400.,       0.,    4800.,    2400.,       0.,    9600.]])

In [16]:
b1.fuerza_local()*1e-3

array([-157.02710519,  106.05122292,  360.44136804,  157.02710519,
       -106.05122292,  275.86596946])

In [17]:
b5 = p.barras()[4]

In [18]:
b5.carga_equiv_local()*1e-3

array([ 4.91884467e-15, -6.48999230e+01, -1.17000000e+02,  4.91884467e-15,
       -6.48999230e+01,  1.17000000e+02])

In [19]:
b5.fuerza_local()*1e-3

array([ 93.29097262,  59.07024524,  27.00178948, -93.29097262,
        70.72960068, -90.05939531])

In [20]:
p.fuerza_gdl()*1e-3

array([  80.,    0.,    0.,   36.,   54., -117.,   76.,   54.,  117.])

In [21]:
b1.desplaz_global()

array([ 0.        ,  0.        ,  0.        ,  0.18542365,  0.00041874,
       -0.01761987])

In [22]:
b1.desplaz_local()

array([ 0.        ,  0.        ,  0.        ,  0.00041874, -0.18542365,
       -0.01761987])

In [24]:
p.cargas_barras

{5: (6656.402354702748, 9984.603532054125)}

In [29]:
import numpy as np

In [40]:
for t in p.cargas_nodales:
    print(np.asarray(p.cargas_nodales[t]))

[80000.     0.     0.]
[40000.     0.     0.]


In [43]:
for r in p.restricciones.values():
    print(r)

(1, 1, 1)
(1, 1, 1)
