In [1]:
import numpy as np

import analisa.edeb as est

ModuleNotFoundError: No module named 'analisa'

In [20]:
# Datos
nudos_csv = 'csv/nudos_k65.csv'
barras_csv = 'csv/barras_k65.csv'
materiales = [est.Material(200e9)]  # Lista de materiales

In [21]:
A = 4740*1e-3**2
Iz = 22.2e-6
secciones = [est.Seccion(area=A, inercia_z=Iz)]  # Lista de secciones
restricciones = {1: (1,1,1), 3: (1,1,0)}  # Restricciones
cargas_estaticas = {2: (120e3, -37.5e3, 125e3), 3: (0, 0, 75e3)}

In [22]:
# Cargas dinámicas
cargas_armonicas = {2: ((100e3, 15), 0, 0)}

In [23]:
# Resolución de la estructura
coords, elementos = est.preprocesamiento(nudos_csv, barras_csv, materiales, secciones)
p2d = est.Portico(coords=coords, restricciones=restricciones,elementos=elementos, cargas_nodales=cargas_estaticas)

In [25]:
p2d.procesamiento();


Configuración de nudos y barras...
Ensamble de matrices globales...
Resolución del problema estático...
Listo, preguntá lo que quieras.


In [33]:
import numpy as np

In [34]:
P = np.array([2,3,5])
omega2 = np.array([-2, 1, 5])
C = np.array([7,8,9])
D = np.array([-5,0.6,-2])
t = np.linspace(0, 5)

In [36]:
qn = P/omega2 * (C*np.sin(.5*2) + D*np.cos(.5*2))
qn

array([-3.18878536, 21.16784779,  6.49263425])

In [45]:
d = np.array([[1,0,-2],[4,5,6]])
ds = d.sum(axis=0)
ds

array([5, 5, 4])

In [47]:
np.e**(np.array([1,2,3]))

array([ 2.71828183,  7.3890561 , 20.08553692])

In [19]:
p2d.modos_max_uno()

array([[-0.00393307,  0.01900132,  0.28993314, -1.        ],
       [-0.00837808, -0.0103288 , -1.        , -0.36874071],
       [-0.89776433,  0.4892676 ,  0.02166389,  0.51540023],
       [ 1.        ,  1.        , -0.40513064,  0.2428552 ]])